### ISSUE TITLE
Include example test in test/index.js

### ISSUE THREAD

**Issue by Flet** [ngoldman/module-init#14]
It would be nice to include a simple test in `test/index.js` instead of being blank.

Maybe as simple as:
```
var test = require('tape')

test('Example Test', function (t) {
  t.plan(1)
  t.error('No tests defined.')
})
```

I realize this is complicated by the fact that a module could be `standard` or `semistandard` too... :(

**Comment by bcomnes** [comment]
Run through (semi)standard-format?

**Comment by ngoldman** [comment]
We could modify the template to handle each case. Would need to handle conditionals better (this would help fix #15 too).

**Comment by Flet** [comment]
Hmm, instead of dealing with this in the template, could it do this:
- add mustache template for index/test.js (and maybe index.js too... blank files make me sad).
- add an npm script to  the new `package.json.mustache`: 
```
"format": "{{pkgLinter}} -F"
```
- after the `exec('npm install')` line in [index.js](https://github.com/ngoldman/module-init/blob/master/index.js#L106), do `exec('npm run format')` to reformat in their choosen `*standard` format.

**Comment by ngoldman** [comment]
that makes sense too. are the formatters in good shape right now? `standard -F` was still missing most cases last I checked (but may be adequate for something as short as the above case).

**Comment by ngoldman** [comment]
Working on finally getting this one in.

**Comment by Flet** [comment]
Nice, thanks!
