### ISSUE TITLE
use npm-name to check for availability

### ISSUE THREAD

**Issue by ngoldman** [ngoldman/module-init#17]
Is it worthwhile to use https://github.com/sindresorhus/npm-name to check for name availability on npm before picking a name?

@bcomnes @Flet

**Comment by bcomnes** [comment]
Yeah I think so.  Otherwise I'm just manualy checking.

**Comment by Flet** [comment]
hehe you must have seen my star :)

Yes, however `npm-name` does not support http proxies at all... which breaks me. :(

**Comment by ngoldman** [comment]
@flet yep :)

that's inconvenient re: http proxies. will keep that in mind when I take a closer look
