### ISSUE TITLE
Move github.user check to the top

### ISSUE THREAD

**Issue by Flet** [ngoldman/module-init#2]
It would be nice to fail quickly if github user does not exist in git config by checking before asking questions. This ensures a user does not need to fill out everything again if they don't have it.

**Comment by Flet** [comment]
Excellent idea for this module btw :+1:

**Comment by ngoldman** [comment]
Thanks @Flet! It's based mostly off of @finnp's https://github.com/finnp/create-module. I wanted to do enough things differently that I didn't want to bikeshed upon that project.

Also yes, fail earlier makes sense to me. :+1:

**Comment by ngoldman** [comment]
@Flet fixed! Should be better now.
