### ISSUE TITLE
Add downloads badge to the README

### ISSUE THREAD

**Issue by Flet** [ngoldman/module-init#20]
Any thoughts on adding a download badge to the README?

[![npm][npm-image]][npm-url]
[![travis][travis-image]][travis-url]
[![downloads][downloads-image]][downloads-url]

[npm-image]: https://img.shields.io/npm/v/module-init.svg?style=flat-square
[npm-url]: https://www.npmjs.com/package/module-init
[travis-image]: https://img.shields.io/travis/ngoldman/module-init.svg?style=flat-square
[travis-url]: https://travis-ci.org/ngoldman/module-init
[downloads-image]: https://img.shields.io/npm/dm/module-init.svg?style=flat
[downloads-url]: https://npmjs.org/package/module-init

**Comment by ngoldman** [comment]
Seems unnecessary to me, especially for a project that's just starting. Npm badge is useful information because it shows version number and links to the package. Travis badge because it's an indicator of project health. What purpose does download badge serve?

**Comment by Flet** [comment]
I like that it makes information symmetrical to what is on npmjs.com, which can avoid a trip there for users who may be vetting the package. I agree it's not integral.

**Comment by ngoldman** [comment]
I guess I'm a little skittish about it because I don't want to overload every readme with badges. I can see how it does provide an idea of how much the package is getting used -- but if you're just initializing a new module that number is always going to be zero.

**Comment by Flet** [comment]
Cool, makes sense.
