### ISSUE TITLE
false negative for module name

### ISSUE THREAD

**Issue by ngoldman** [ngoldman/module-init#23]
Getting a false negative for `parse-wkid` from [can-haz-package](https://www.npmjs.com/package/can-haz-package).

Will investigate further when I have a minute. cc @Flet

**Comment by ngoldman** [comment]
(as in `>> Sorry, that package name is taken! :(` when it's actually free)

**Comment by ngoldman** [comment]
I think I'm going to let people create the package even if the name's taken and just have it be a warning. There's cases where it's not at all relevant if the package name is available on npm (private module, private npm).

**Comment by Flet** [comment]
Yeah I agree, users should be able to bypass this check.

**Comment by ngoldman** [comment]
I'm getting stopped by any name right now... I'm going to have to remove it for now.

```
? name: (blarg) blarg123456789
>> Sorry, that package name is taken! :(
```

**Comment by Flet** [comment]
OK. Really strange... If I send a patch with a way to easily bypass would you accept it?

**Comment by ngoldman** [comment]
Only if it's accurate in terms of reporting package name availability. I'll have to test more to figure it out

**Comment by ngoldman** [comment]
Closing this for now.
