### ISSUE TITLE
make npm install step optional

### ISSUE THREAD

**Issue by ngoldman** [ngoldman/module-init#33]
I'd like to stop the `npm install` step from being automatic and prompt for it instead as it often takes a long time just to install tape, tap-spec, and standard, and I'd rather run npm install myself afterwards sometimes.

Example workflow:

```
? name: derp
? version: 1.0.0
? description:
? keywords:
? license: ISC
? contributing: Yes
? linter: standard
Initialized empty Git repository in /Users/ng/dev/github/module-init/derp/.git/
✓ .gitignore created
✓ .travis.yml created
✓ CHANGELOG.md created
✓ CONTRIBUTING.md created
✓ LICENSE created
✓ README.md created
✓ package.json created
✓ index.js created
✓ test/index.js created
? npm install: (Y/n) n
✓ derp initialized
```

This would speed things up quite a bit for me, especially when working on low bandwidth connections.

Want to run it by the regular contributors/maintainers (@flet @bcomnes @paulcpederson) before I do it in case this is a blocker for anyone

**Comment by Flet** [comment]
Totally cool with this!
