### ISSUE TITLE
add options for contributing

### ISSUE THREAD

**Issue by ngoldman** [ngoldman/module-init#4]
Contributing needs to be a `list` rather than an `input`.

Currently it's just [Open-2](https://github.com/ngoldman/open-2-contributing). I don't know of many templates for Contribution Guidelines other than https://github.com/jden/CONTRIBUTING.md. Would be nice to have some options. At the very least:

* Open-2
* None

@jden would you say https://github.com/jden/CONTRIBUTING.md has any kind of name in terms of what sort of contributing document it is? My impulse is to call it "Inclusive".

**Comment by jden** [comment]
I like the name "Inclusive". It targets the non-directly-code-related aspects of contribution guidelines, and is modeled after rust. It aims to give guidance on social aspects of project development, articulate the particular kinds of contributions the project is looking for (eg an "onramp" for new contributors) and to clarify project channels of communication.

**Comment by ngoldman** [comment]
:+1: @jden thanks!

**Comment by ngoldman** [comment]
going with just a (y/n) default boilerplate that blends elements from "open open" and https://github.com/jden/CONTRIBUTING.md since neither cover exactly what I was going for. good stuff all around :+1:
