### ISSUE TITLE
create repo on github

### ISSUE THREAD

**Issue by Flet** [ngoldman/module-init#9]
@mattdesl has this neat util that may be relevant: https://github.com/mattdesl/ghrepo

**Comment by ngoldman** [comment]
It does the job but it's CLI only (and io.js only I think). I'd like to be able to use the same token for the repo creation step for the travis-ci hook step.

My plan was to use [ghauth](https://github.com/rvagg/ghauth) to prompt auth & store token, then use request to make the repo creation call and travisjs to make the travis-ci call.

**Comment by bcomnes** [comment]
http://stackoverflow.com/a/7563830

**Comment by ngoldman** [comment]
I think the create a github repo and initialize a travisjs hook ideas are worthwhile but maybe out of scope for this project. I feel like `module-init` is pretty much done in terms of functionality -- future updates should focus on changes related to broader node conventions (like when es6 becomes the norm or we all start writing php again or something). For now I think `module-init` works well in its current form as a sort of `npm init` for the overzealous :)

I might take a crack at integrating `module-init` into another project that would do the github repo and travisjs hook parts too -- a sort of swiss army knife cli for managing module lifecycle.

Thanks @flet and @bcomnes for helping make this into a thing I use all the time.

**Comment by bcomnes** [comment]
:+1:
